### PR TITLE
Add react-native example

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
This is a better try of adding react-native as an example. It does not work as for the reasons disussed in openzipkin/zipkin-js#128

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
@adriancole Sorry for the long delay between updated PRs, haven't had the time to look into these issues

**Comment by DanielMSchmidt** [comment]
@adriancole I am not 100% sure this works now, I am currently experiencing that the zipkin UI shows me my serviceName and spanName, but I can not get it to show a single trace. I am a bit clueless actually how this is possible.

**Comment by codefromthecrypt** [comment]
could be possible if timestamps are missing or incorrect. if you don't know
a trace ID you can try searching for all data.. set lookback to current
time in millis

ex  curl -s localhost:9411/api/v1/traces?lookback=1509199572000

**Comment by codefromthecrypt** [comment]
or curl -s localhost:9411/api/v2/traces?lookback=1509199572000

for v2 format

**Comment by codefromthecrypt** [comment]
@DanielMSchmidt might be a wild goose chase, but here's what I'd blindly do...
first if you are seeing service names definitely spans are arriving, you've a trace. make your app print the trace ID then try to curl it like http://localhost:9411/api/v2/trace/that_id

if timestamps show incorrectly, look at the batchrecorder, you'll notice it uses time.js. maybe this isn't working right in react. remember I'm just guessing so don't immediately blame anything.

gonna hit the sack but keep us posted!

**Comment by codefromthecrypt** [comment]
giving a try

**Comment by codefromthecrypt** [comment]
bug upstream.. I'll fix. basically accidentally prevented the default service name 'unknown'

**Comment by DanielMSchmidt** [comment]
Wow, nice that your found that, awesome job!

**Comment by codefromthecrypt** [comment]
>
> Wow, nice that your found that, awesome job!
>
one gets ok at troubleshooting data issues when only looking at zipkin for
> 2years :P

**Pull request merged**
